### ISSUE TITLE
how to disabled "This action is not available in the demo ?"

### ISSUE THREAD

**Issue by dyazincahya** [joni2back/php-classic#1]
how to disabled This action is not available in the demo ?

**Comment by joni2back** [comment]
If you are talking about [angular-filemanager](https://github.com/joni2back/angular-filemanager), you should write the rest of the code of **[handler.php](https://github.com/joni2back/angular-filemanager/blob/master/bridges/php/handler.php)**
Because the idea is to adapt the backend controller to your own requirement.
